default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: <%= ENV['RAILS_MYSQL_DATABASE_USERNAME'] || 'root' %>
  password: <%= ENV['RAILS_MYSQL_DATABASE_PASSWORD'] || 'root' %>
  host: <%= ENV['RAILS_MYSQL_DATABASE__HOST'] || 'localhost' %>

development:
  <<: *default
  database: myboard_development
  socket: <%= ENV['RAILS_MYSQL_DATABASE_SOCKET'] || '/tmp/mysql.sock'%>

test:
  <<: *default
  database: myboard_test
  socket: <%= ENV['RAILS_MYSQL_DATABASE_SOCKET'] %>

production:
  <<: *default
  database: myboard_production
  username: root
  password:

# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
#default: &default
#  adapter: sqlite3
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000
#
#development:
#  <<: *default
#  database: db/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
#test:
#  <<: *default
#  database: db/test.sqlite3
#
#production:
#  <<: *default
#  adapter: postgresql
#  encoding: unicode
#  pool: 5
#  <<: *default
#  database: db/production.sqlite3
